### ISSUE TITLE
main metoda

### ISSUE THREAD

**Issue by HalimMarmarac** [HalimMarmarac/NizBrojeva#7]
testirati sve implemetirane metode u klasi Metode

**Comment by HalimMarmarac** [comment]
done

**Comment by Kobe929** [comment]
U main metodi ne ispisuje sortiran niz kako treba.

**Comment by Kobe929** [comment]
Linija 30, ispiše uneseni niz, sitnica ali eto :D

**Comment by HalimMarmarac** [comment]
done done done

**Comment by Kobe929** [comment]
nice, super
